### ISSUE TITLE
Double click to open folders in Files

### ISSUE THREAD

**Issue by staniki** [pantheon-tweaks/pantheon-tweaks#115] opened 2021-09-17 07:43 UTC
Will the function of double-clicking on folders to open them be added?

**Comment by ryonakano** [comment] 2021-09-17 09:33
Closing as a duplicate of #76. The single-click option was removed from Files itself so we removed it. Adding it back will crash the plug, as per [the release note](https://github.com/pantheon-tweaks/pantheon-tweaks/releases/tag/1.0.0):

> * Remove preferences causing the plug crash

**Closed by ryonakano** 2021-09-17 09:33 UTC
