### ISSUE TITLE
Disable single click option not found

### ISSUE THREAD

**Issue by out0** [pantheon-tweaks/pantheon-tweaks#92] opened 2021-08-12 03:20 UTC
Disable single click option not found. Is it possible to add this?

**Comment by ryonakano** [comment] 2021-08-12 03:49
Closing as a duplicate of #76. The single-click option was removed from Files itself so we removed it. Adding it back will crash the plug, as per [the release note](https://github.com/pantheon-tweaks/pantheon-tweaks/releases/tag/1.0.0):

> * Remove preferences causing the plug crash

**Closed by ryonakano** 2021-08-12 03:49 UTC
