### ISSUE TITLE
Not showing files single-click option

### ISSUE THREAD

**Issue by Panniz** [pantheon-tweaks/pantheon-tweaks#78] opened 2021-06-26 22:52 UTC
![Schermata da 2021-06-27 00-18-24](https://user-images.githubusercontent.com/62348033/123527170-a0debb00-d6dd-11eb-88f7-181498bb639f.png)

I tried

 `gsettings set io.elementary.files.preferences single-click false`

But gives back  _key single-click_ is _missing_.

**Comment by ryonakano** [comment] 2021-06-26 23:10
Closing as a duplicate of #76. The single-click option was removed from Files itself.

**Closed by ryonakano** 2021-06-26 23:10 UTC
