### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by George4All** [pantheon-tweaks/pantheon-tweaks#69] opened 2021-04-17 09:23 UTC
I recently re-downloaded elementary OS on my laptop, since I got a new SSD and I decided I wanted a fresh install. Whenever I try to to run the command `sudo apt install pantheon-tweaks` keeps giving me this error:
```
george4all@george4all-NKx0Sx:~$ sudo apt install pantheon-tweaks
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pantheon-tweaks is already the newest version (1.0-0~202104120741~ubuntu6.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pantheon-tweaks : Depends: libgranite6 (>= 0.5) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
When I try 'george4all@george4all-NKx0Sx:~$ sudo apt --fix-broken install'
This happens: 
```
george4all@george4all-NKx0Sx:~$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libgranite6
The following NEW packages will be installed:
  libgranite6
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/168 kB of archives.
After this operation, 652 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 195261 files and directories currently installed.)
Preparing to unpack .../libgranite6_5.5.0+r1759+pkg117~ubuntu5.1.7.1_amd64.deb ...
Unpacking libgranite6:amd64 (5.5.0+r1759+pkg117~ubuntu5.1.7.1) ...
dpkg: error processing archive /var/cache/apt/archives/libgranite6_5.5.0+r1759+pkg117~ubuntu5.1.7.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libgranite.so.5.5.0', which is also in package libgranite5:amd64 5.5.0+r1759+pkg119~ubuntu5.1.7.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libgranite6_5.5.0+r1759+pkg117~ubuntu5.1.7.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ryonakano** [comment] 2021-04-17 09:47
Closing as a duplicate of #68

**Closed by ryonakano** 2021-04-17 09:47 UTC
