### ISSUE TITLE
Unable to install on Elementary OS 5.1.7 Hera via the PPA:

### ISSUE THREAD

**Issue by SaintFenix** [pantheon-tweaks/pantheon-tweaks#45] opened 2020-11-15 18:33 UTC
Attempted to install on Elementary OS 5.1.7 Hera via the PPA, and was able to add it however was stopped with a:

`The repository 'http://ppa.launchpad.net/philip.scott/pantheon-tweaks/ubuntu bionic Release' does not have a Release file.`

I added it using the recommended method in the README.md but have had no luck.

**Comment by ryonakano** [comment] 2020-11-15 22:32
Closing as a duplicate of #39. Pantheon Tweaks supports only Odin that is the next major version of elementary OS. For Hera or below please use elementary Tweaks instead.

**Closed by ryonakano** 2020-11-15 22:32 UTC
