### ISSUE TITLE
Partial Dark theme coverage (5.1.7 Hera) (LEGACY)

### ISSUE THREAD

**Issue by phoenix277yt** [pantheon-tweaks/pantheon-tweaks#42] opened 2020-10-28 12:08 UTC
The "prefer dark variant" option in ElementaryTweaks seems to work partially.
I have no experience of this happening before on Elementary Os 0.3 all the way to 5.1.0 where I left, Now its on to 5.1.3 and this happens.
![Screenshot from 2020-10-28 17 36 08](https://user-images.githubusercontent.com/73348506/97433838-24c08780-1944-11eb-8a68-1a680a9d262a.png)
It works everywhere except the settings, applications menu and the navbar (the calendar, sound, networking and power).
I just want to know if it's something that elementary tweaks does now or it's my pc.

**Comment by ryonakano** [comment] 2020-10-28 12:24
Closing as a duplicate of https://github.com/elementary-tweaks/elementary-tweaks/issues/146. This is a side-effect issue of partial support for official dark mode in System Settings on the latest Hera, so we can't take any actions in the scope of elementary Tweaks.

Once the next major version of elementary OS is released, the window of System Settings will respect the dark mode preference which can be found in Desktop→Appearance (not the "prefer dark" preference in elementary Tweaks).

**Closed by ryonakano** 2020-10-28 12:24 UTC
