### ISSUE TITLE
Cursor theme does not apply globally

### ISSUE THREAD

**Issue by HanJoHibender** [pantheon-tweaks/pantheon-tweaks#254] opened 2024-11-12 08:13 UTC
OS version: Elementary OS 7.1 Horus

Steps taken:

- Installed flathub version of pantheon-tweaks 
- Downloaded Qogir icon theme
- Put the icon theme in `~/.icons/`
- Selected custom cursor theme 
- Logout
- Login

Exptected result:
Globally changed cursor

Result:
Cursor is changed in some cases, but not on the desktop or system native apps

I've also tried modifying the cursor folder read access with `chmod +r` but that did not help either.

Hint: I remember in Linux Mint I had the same problem, I could solve it by elevating the settings menu to super user and setting the custom cursor theme.

**Comment by HanJoHibender** [comment] 2024-11-12 09:42
As a temporary fix using `lxappearance` seems to set the cursor theme globally, I don't know what it does differently though.

**Comment by ryonakano** [comment] 2024-11-25 22:55
Hmm, I can't reproduce your issue on a fresh installation of elementary OS 7.1. I checked the shape of the cursor in System Settings, Files, Mails, etc. but Qogir seems to be applied as expected:

![Screenshot From 2024-11-26 07-50-35](https://github.com/user-attachments/assets/518c9a96-7a79-401d-ad7c-835bca7db222)

- Did you downloaded Qogir icon theme from https://www.pling.com/p/1296407/?
- How did you place the downloaded themes? Did you extract it using File Roller and place it in the same way in my screenshot above?

**Comment by HanJoHibender** [comment] 2024-11-25 23:17
Hi Ryonakano,

I've dowloaded the theme from:
https://github.com/vinceliuice/Qogir-icon-theme

It has a script for setup, which I tried. 
But  I had the problem of it not applying everywhere.

After some research I also found out that flatpack distributions of apps don't tend to respect all the settings for custom themes and cursors. I've resorted to using .deb variants instead.

But in the end I put my cursor theme in the .icons folder of root. I did the same for my gtk theme and used an elevated pantheon-tweaks window to set the themes for root.

It partially worked, but as mentioned before using lxappearance did the trick somehow. Although it took two times of applying it to be consistent.

It might not be a problem with pantheon-tweaks at all. My installation was also fresh when I started modifying the themes.

If it's not reproducible consider it a non issue.

**Comment by ryonakano** [comment] 2024-11-30 12:45
Thank you for your detailed info. I can confirm the cursor theme are not applied globally when I run the setup script in the repository. However, it is applied as expected when I set the destination directory of the themes to `~/.icons` instead of the default `~/.local/share/icons`, which sounds a duplicate of #90.

As you mentioned I also think this is an issue of Pantheon Tweaks, because its job is just to set a preferred cursor theme and loading the preferred one is not its job. So I'll close this issue.

You might want to try installing your icons into `~/.icons` without the lxappearance workaround when you perform a fresh installation of elementary OS. I hope it would work as expected.

**Closed by ryonakano** 2024-11-30 12:45 UTC
Labels: status: incomplete
